server:
  port: 8800
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 查看日志
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    #mysql8系列要加个cj
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql.ryan.com:3306/guigu-auth?characterEncoding=utf-8&useSSL=false
    username: root
    password: Powervotex@2019

  redis:
    host: 192.168.1.90
    port: 63791
    database: 0
    timeout: 1800000
    password: ht@123
    jedis:
      pool:
        max-active: 20 #最大连接数
        max-wait: -1    #最大阻塞等待时间(负数表示没限制)
        max-idle: 5    #最大空闲
        min-idle: 0     #最小空闲
